steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/site-vacuum-crate:$COMMIT_SHA', '.']
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/site-vacuum-crate:$COMMIT_SHA']
    id: 'push-image'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'site-vacuum-crate'
      - '--image=gcr.io/$PROJECT_ID/site-vacuum-crate:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--port=8000'
    id: 'deploy-to-cloud-run'

images:
  - 'gcr.io/$PROJECT_ID/site-vacuum-crate:$COMMIT_SHA'

timeout: '1800s' 

options:
  logging: CLOUD_LOGGING_ONLY
